services:
  slippi-dolphin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dolphin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/config:/config
    ports:
      - 3000:3000
      - 3002:3001
    shm_size: "1gb"
    restart: unless-stopped
