services:
  slippi-dolphin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dolphin
    environment:
     # - PUID=1000
     # - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - ./roms:/roms
    ports:
      - 3000:3000
      - 3502:3001
    shm_size: "1gb"
    restart: unless-stopped
