[paths]
ffmpeg = "ffmpeg"
slippi_playback = "/config/squashfs-root/AppRun.wrapped"
ssbm_iso = "/roms/Melee.iso"

[dolphin]
backend = "OGL"
resolution = "720p"
bitrate = 2000

[ffmpeg]
volume = 100

[runtime]
parallel = 2
