[paths]
ffmpeg = "ffmpeg"
slippi_playback = "/dolphin/Slippi_Playback_Mainline-x86_64.AppImage"
ssbm_iso = "/roms/Melee.iso"

[dolphin]
backend = "OGL"
resolution = "720p"
bitrate = 2000

[ffmpeg]
volume = 100

[runtime]
parallel = 2
